import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://login.salesforce.com/');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('gauthami.vn@testleaf.com');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Qeagle@123');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByRole('textbox', { name: 'Verification Code' }).click();
  await page.getByRole('textbox', { name: 'Verification Code' }).fill('');
  await page.getByRole('textbox', { name: 'Verification Code' }).click();
  await page.getByRole('textbox', { name: 'Verification Code' }).fill('312889');
  await page.getByRole('button', { name: 'Verify' }).click();
  await page.goto('https://orgfarm-6d28dcc693-dev-ed.develop.lightning.force.com/lightning/page/home');
  await page.getByRole('button', { name: 'App Launcher' }).click();
  await page.getByRole('button', { name: 'View All Applications' }).click();
  await page.getByRole('combobox', { name: 'Search apps or items...' }).click();
  await page.getByRole('combobox', { name: 'Search apps or items...' }).fill('Leads');
  await page.getByRole('link', { name: 'Leads' }).click();
  await page.getByRole('button', { name: 'New' }).click();
  await page.getByRole('combobox', { name: 'Salutation' }).click();
  await page.locator('span').filter({ hasText: 'Mrs.' }).first().click();
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('Gauthami');
  await page.getByRole('textbox', { name: 'Last Name' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).fill('VN');
  await page.getByRole('dialog', { name: 'New Lead' }).click();
  await page.getByRole('dialog', { name: 'New Lead' }).click();
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await page.getByRole('button', { name: 'Close error dialog' }).click();
  await page.getByRole('button', { name: 'Error' }).click();
  await page.locator('#combobox-button-1291').click();
  await page.getByRole('button', { name: 'Close error dialog' }).click();
  await page.getByRole('textbox', { name: 'Company' }).click();
  await page.getByRole('textbox', { name: 'Company' }).fill('Q');
  await page.locator('#sectionContent-1353').click();
  await page.getByRole('textbox', { name: 'Company' }).click();
  await page.getByRole('textbox', { name: 'Company' }).fill('Qeagle');
  await page.getByRole('button', { name: 'Save', exact: true }).click();
});